version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    links:
      - client
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
  client:
    container_name: client
    image: node:12.16.1
    volumes:
      - ./cliente/:/client/
    command: sh -c "cd /client/ && npm install -g serve && serve -s build/ -p 3000"
    environment:
      API_URL: 'http://localhost/api'
    restart: always
  api:
    container_name: api
    image: node:12.16.1
    volumes:
      - ./server:/api/
    command: sh -c "cd /api/ && mkdir -p uploads/avatar && yarn install && yarn start"
    links:
      - db_mongo
    environment:
      DB_URL: 'mongodb://db_mongo:27017/lims'
    restart: always
  db_mongo:
    container_name: db_mongo
    image: mongo:4.2.3
    volumes:
      - ./mongo:/data/db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
    restart: always

